title: "Mi Blog para Desarrollo de Aplicaciones en Red"
description: "Ejemplo de blog estático creado con Jekyll"
author: "Juan Guillermo Sandoval Montero"
lang: "es"

baseurl: "/BlogUNIR"

permalink: /:year/:month/:day/:title/
